### ISSUE TITLE
Not able to build with VS2015

### ISSUE THREAD

**Issue by JasonYanxx** [zabirauf/icsharp#57]
the code `public bool IsError { get => !(CompileError == null && ExecuteError == null); }` in source project make my building wrong!
Here is the error:
'Error	CS0161	'ExecutionResult.IsError.get': not all code paths return a value	Kernel'

**Comment by JasonYanxx** [comment]
use`public bool IsError { get { return !(CompileError == null && ExecuteError == null); } }` instead,then rebuild the project, eventually be fine!

**Comment by zabirauf** [comment]
I believe this might be happening because the msbuild installed by VS2015 doesn't support the newer version of C#. Can you try updating the VS 2015 or the msbuild version to latest and try again. Hopefully that should resolve the problem.

**Comment by JasonYanxx** [comment]
> I believe this might be happening because the msbuild installed by VS2015 doesn't support the newer version of C#. Can you try updating the VS 2015 or the msbuild version to latest and try again. Hopefully that should resolve the problem.

**Comment by JasonYanxx** [comment]
Indeed，I've updated `msbuild` to the latest version,i.e,6.10, but I still failed to build the project. The error mainly focus on the code below :`public bool IsError { get => !(CompileError == null && ExecuteError == null); }`. I rewrite this code with `public bool IsError { get { return !(CompileError == null && ExecuteError == null); } } `, and it works.
